# Generated by Django 4.2 on 2023-04-03 18:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=150, verbose_name=accounts.models.CustomUser)),
                ('description', models.TextField(max_length=600)),
                ('slug', models.SlugField(max_length=400)),
                ('address', models.CharField(max_length=200)),
                ('social', models.URLField(blank=True)),
            ],
        ),
    ]
