# Generated by Django 4.2 on 2023-04-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='social',
            field=models.URLField(),
        ),
    ]
