# Generated by Django 4.2 on 2023-04-03 20:32

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userpost_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='author',
            field=models.ForeignKey(default=accounts.models.CustomUser, max_length=150, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
