# Generated by Django 4.2 on 2023-04-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='social',
            field=models.URLField(blank=True, null=True),
        ),
    ]
