# Generated by Django 4.2 on 2023-04-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userpost_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='social',
        ),
    ]
