# Generated by Django 4.2 on 2023-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=300), max_length=400),
        ),
    ]
